lev5/app5/urls.py
from django.conf.urls import url
from app5 import views

# SET THE NAMESPACE!
app_name = 'app5'


urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

lev5/lev5/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app5 import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^admin/', admin.site.urls),
    url(r'^app5/',include('app5.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

lev5/app5/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)

	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to= 'profile_pics',blank=True)

	def __str__(self):
		return self.user.username

lev5/app5/forms.py
from django import forms
from django.contrib.auth.models import User
from app5.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

lev5/app5/views.py
from django.shortcuts import render
from app5.forms import UserForm,UserProfileInfoForm
# Create your views here.


from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

def index(request):
	return render(request,'app5/index.html')

@login_required
def special(request):
	return HttpResponse('You are logged in, Nice!')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def register(request):

	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.errors, profile_form.errors)

	else:
		user_form= UserForm()
		profile_form=UserProfileInfoForm()

	return render(request,'app5/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
	
	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse('Account not active.')

		else:
			print("Someone tried to login & failed.")
			print("Username:{} and password:{}".format(username,password))
			return HttpResponse("Invalid login details supplied.")
	else:
		return render(request,'app5/login.html',{})

lev5/templates/app5/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
				<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
				<li><a class="navbar-link" href="{% url 'app5:register' %}">Register</a></li>

				{% if user.is_authenticated %}
	        	    <li><a href="{% url 'logout' %}">Logout</a></li>
		        {% else %}
	            	<li><a class="navbar-link" href="{% url 'app5:user_login' %}">Login</a></li>
	    	    {% endif %}


			</ul>
		</div>
	</nav>
	<div class="container">
	{% block body_block %}
	{% endblock %}
	</div>
		
</body>
</html>

lev5/templates/app5/index.html
{% extends "app5/base.html" %}
{% block body_block %}

<div class="container">
	<div class="jumbotron">
		<h1>Django Level Five</h1>
		{% if user.is_authenticated %}
			<h2>Welcome {{ user.username }}!</h2>
		{% else %}
			<h2>Welcome to the site!</h2>
		{% endif %}
	</div>
</div>

{% endblock %}

lev5/templates/app5/login.html
{% extends 'app5/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'app5:user_login' %}">
          {% csrf_token %}
          
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

lev5/templates/app5/registration.html
{% extends "app5/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
      
    </div>

  </div>

{% endblock %}